import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template:"%s | Pokemon Search App",
    default: "Pokemon Search App"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#004368] shadow-[rgba(0,0,0,0.07)_0px_0px_12px] px-5 py-6 text-lg text-white ">
          Pokemon search App
        </div>
        <div className="container m-auto p-5" >
        {children}
        </div>
      </body>
    </html>
  );
}
